<a href="https://colab.research.google.com/github/ankit6102001/Python-Machine-learning-Deep-learning/blob/main/Text_classification(countVectorizer_Tfdfvectorizer).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
#document->it is simply a string representing a text.
#corpus->it is a group of documents as list/array.

doc1='food is # good! _@ 2019'
doc2='& Food # is * tasty'
doc3='quality is Good'
doc4='service is Poor poor means very poor'
doc5='food is not good'
doc6='cheap quality'

target=['pos','pos','pos','neg','neg','neg']

sw=stopwords.words("english")
sw.remove('not')

def remove_punch(doc):
    return re.sub("[^a-z ]","",doc).strip()

def remove_sp(doc):
    tokens=word_tokenize(doc)
    s2=""
    for i in tokens:
        if(i not in sw):
            s2=s2+i+" "
    return s2.strip()

corpus=[doc1,doc2,doc3,doc4,doc5,doc6]
corpus1=list(map(str.lower,corpus))
corpus2=list(map(remove_punch,corpus1))
corpus3=list(map(remove_sp,corpus2))

In [ ]:
corpus3

['food good',
 'food tasty',
 'quality good',
 'service poor poor means poor',
 'food not good',
 'cheap quality']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer()
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
dense_matrix

array([[0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 3, 0, 1, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [ ]:
print(cv.get_feature_names())

['cheap', 'food', 'good', 'means', 'not', 'poor', 'quality', 'service', 'tasty']


In [ ]:
print(sp_matrix)

  (0, 1)	1
  (0, 2)	1
  (1, 1)	1
  (1, 8)	1
  (2, 2)	1
  (2, 6)	1
  (3, 7)	1
  (3, 5)	3
  (3, 3)	1
  (4, 1)	1
  (4, 2)	1
  (4, 4)	1
  (5, 6)	1
  (5, 0)	1


In [ ]:
cv=CountVectorizer(binary=True)
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
dense_matrix

array([[0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [ ]:
cv=CountVectorizer(binary=True,ngram_range=(1,1))
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
print(cv.get_feature_names())

['cheap', 'food', 'good', 'means', 'not', 'poor', 'quality', 'service', 'tasty']


In [ ]:
cv=CountVectorizer(binary=True,ngram_range=(1,2))
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
print(cv.get_feature_names())

['cheap', 'cheap quality', 'food', 'food good', 'food not', 'food tasty', 'good', 'means', 'means poor', 'not', 'not good', 'poor', 'poor means', 'poor poor', 'quality', 'quality good', 'service', 'service poor', 'tasty']


In [ ]:
cv=CountVectorizer(binary=False,ngram_range=(1,3),max_features=10)
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
print(cv.get_feature_names())

['cheap', 'food', 'good', 'poor', 'poor poor', 'poor poor means', 'quality', 'quality good', 'service', 'service poor']


In [ ]:
dense_matrix

array([[0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 3, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0]], dtype=int64)

In [ ]:
corpus3

['food good',
 'food tasty',
 'quality good',
 'service poor poor means poor',
 'food not good',
 'cheap quality']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tv=TfidfVectorizer(binary=False,ngram_range=(1,1))
dense_matrix=tv.fit_transform(corpus3).toarray()
print(tv.get_feature_names())
dense_matrix

['cheap', 'food', 'good', 'means', 'not', 'poor', 'quality', 'service', 'tasty']


array([[0.        , 0.70710678, 0.70710678, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.56921261, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.82219037],
       [0.        , 0.        , 0.64510243, 0.        , 0.        ,
        0.        , 0.7640961 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.30151134, 0.        ,
        0.90453403, 0.        , 0.30151134, 0.        ],
       [0.        , 0.49468646, 0.49468646, 0.        , 0.71454223,
        0.        , 0.        , 0.        , 0.        ],
       [0.77326237, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.6340862 , 0.        , 0.        ]])

In [ ]:
import numpy as np

np.sqrt((1.5596*1.5596)*2)

2.2056074718770793

In [ ]:
1.5596/2.2056

0.7071091766412768

In [ ]:
from sklearn.linear_model import LogisticRegression
cv=CountVectorizer()
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
model=LogisticRegression()
model.fit(dense_matrix,target)
print(model.score(dense_matrix,target))
sample="Food quality was not G_ood"
sample1=sample.lower()
sample2=remove_punch(sample1)
sample3=remove_sp(sample2)
sample4=cv.transform([sample3]).toarray()
model.predict(sample4)

0.8333333333333334


array(['pos'], dtype='<U3')

In [ ]:
from sklearn.linear_model import LogisticRegression
cv=CountVectorizer(ngram_range=(1,2))
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
model=LogisticRegression()
model.fit(dense_matrix,target)
print(model.score(dense_matrix,target))
sample="Food quality was not G_ood"
sample1=sample.lower()
sample2=remove_punch(sample1)
sample3=remove_sp(sample2)
sample4=cv.transform([sample3]).toarray()
model.predict(sample4)

1.0


array(['neg'], dtype='<U3')

In [ ]:
from sklearn.linear_model import LogisticRegression
cv=CountVectorizer(binary=True)
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
model=LogisticRegression()
model.fit(dense_matrix,target)
print(model.score(dense_matrix,target))
sample="Food quality was not G_ood"
sample1=sample.lower()
sample2=remove_punch(sample1)
sample3=remove_sp(sample2)
sample4=cv.transform([sample3]).toarray()
model.predict(sample4)

1.0


array(['pos'], dtype='<U3')

In [ ]:
from sklearn.linear_model import LogisticRegression
cv=CountVectorizer(binary=True,ngram_range=(1,2))
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
model=LogisticRegression()
model.fit(dense_matrix,target)
print(model.score(dense_matrix,target))
sample="Food quality was not G_ood"
sample1=sample.lower()
sample2=remove_punch(sample1)
sample3=remove_sp(sample2)
sample4=cv.transform([sample3]).toarray()
model.predict(sample4)

1.0


array(['neg'], dtype='<U3')

In [ ]:
from sklearn.linear_model import LogisticRegression
cv=TfidfVectorizer()
sp_matrix=cv.fit_transform(corpus3) #returns sparse matrix
dense_matrix=sp_matrix.toarray()
model=LogisticRegression()
model.fit(dense_matrix,target)
print(model.score(dense_matrix,target))
sample="Food quality was not G_ood"
sample1=sample.lower()
sample2=remove_punch(sample1)
sample3=remove_sp(sample2)
sample4=cv.transform([sample3]).toarray()
model.predict(sample4)

1.0


array(['neg'], dtype='<U3')

In [ ]:
import pandas as pd