<a href="https://colab.research.google.com/github/ankit6102001/Python-Machine-learning-Deep-learning/blob/main/voting_classifier_and_open_cv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier,BaggingClassifier,AdaBoostClassifier,VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [ ]:
df=pd.read_csv("d:/dataset/classification/iris.csv")
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
model=RandomForestClassifier(n_estimators=5)
model.fit(X,y)
sample=[1.9,.5,3.5,.8]
print(model.predict([sample]))
print(model.predict_proba([sample]))

[1]
[[0.2 0.8 0. ]]


In [ ]:
#weak_model=KNeighborsClassifier()
weak_model=LogisticRegression(max_iter=500)
model=BaggingClassifier(base_estimator=weak_model,n_estimators=5)
model.fit(X,y)
sample=[1.9,.5,3.5,.8]
print(model.predict([sample]))
print(model.predict_proba([sample]))

[1]
[[0.2159121  0.70269522 0.08139269]]


In [ ]:
model=AdaBoostClassifier(n_estimators=5) #decision tree
model.fit(X,y)
sample=[1.9,.5,3.5,.8]
print(model.predict([sample]))
print(model.predict_proba([sample]))

[0]
[[9.99999921e-01 5.36767571e-08 2.48518262e-08]]


In [ ]:
weak_model=LogisticRegression(max_iter=500)
model=AdaBoostClassifier(base_estimator=weak_model,n_estimators=5) 
model.fit(X,y)
sample=[1.9,.5,3.5,.8]
print(model.predict([sample]))
print(model.predict_proba([sample]))

[1]
[[0.30060387 0.51024779 0.18914834]]


In [ ]:
weak_model=KNeighborsClassifier()
model=AdaBoostClassifier(base_estimator=weak_model,n_estimators=5)
model.fit(X,y)
sample=[1.9,.5,3.5,.8]
print(model.predict([sample]))
print(model.predict_proba([sample]))

ValueError: KNeighborsClassifier doesn't support sample_weight.

In [ ]:
df=pd.read_csv("d:/dataset/classification/iris.csv")
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
weak_model1=KNeighborsClassifier()
weak_model2=LogisticRegression(max_iter=500)
weak_model3=DecisionTreeClassifier()

#voting=hard---->weak models predict class (default in VotingClassifier)
model=VotingClassifier(estimators=[('m1',weak_model1),('m2',weak_model2),('m3',weak_model3)],voting='hard')
model.fit(X,y)
sample=[1.9,.5,3.5,.8]
print(model.predict([sample]))

[1]


In [ ]:
#voting=soft---->weak models predict prob
model=VotingClassifier(estimators=[('m1',weak_model1),('m2',weak_model2),('m3',weak_model3)],voting='soft')
model.fit(X,y)
sample=[1.9,.5,3.5,.8]
print(model.predict([sample]))

[1]


In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
model=KNeighborsClassifier()
cross_val_score(model,X,y,cv=5).mean()

0.9733333333333334

In [ ]:
model=LogisticRegression(max_iter=500)
cross_val_score(model,X,y,cv=5).mean()

0.9733333333333334

In [ ]:
model=DecisionTreeClassifier()
cross_val_score(model,X,y,cv=5).mean()

0.9666666666666668

In [ ]:
model=RandomForestClassifier()
cross_val_score(model,X,y,cv=5).mean()

0.96

In [ ]:
model=AdaBoostClassifier()
cross_val_score(model,X,y,cv=5).mean()

0.9466666666666667

In [ ]:
model=VotingClassifier(estimators=[('m1',weak_model1),('m2',weak_model2),('m3',weak_model3)],voting='soft')
cross_val_score(model,X,y,cv=5).mean()

0.9666666666666668

In [ ]:
import cv2

In [ ]:
cv2.__version__

'4.5.5'

In [ ]:
img=cv2.imread("d:/images/sachin.jpg",cv2.IMREAD_COLOR)
cv2.imshow("color image",img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [ ]:
img=cv2.imread("d:/images/sachin.jpg",cv2.IMREAD_COLOR)
cv2.imshow("color image",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
img_clr=cv2.imread("d:/images/sachin.jpg",cv2.IMREAD_COLOR)
img_gray=cv2.imread("d:/images/sachin.jpg",cv2.IMREAD_GRAYSCALE)
print(type(img_clr),img_clr.ndim,img_clr.shape)
print(type(img_gray),img_gray.ndim,img_gray.shape)

cv2.imshow("color image",img_clr)
cv2.imshow("gray image",img_gray)
cv2.waitKey()
cv2.destroyAllWindows()

<class 'numpy.ndarray'> 3 (606, 420, 3)
<class 'numpy.ndarray'> 2 (606, 420)


In [ ]:
img=cv2.imread("d:/images/sachin.jpg",cv2.IMREAD_COLOR)
img=cv2.resize(img,(300,400))
cv2.imshow("color image",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
img=cv2.imread("d:/images/sachin.jpg",cv2.IMREAD_COLOR)
img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("color image",img)
cv2.imshow("gray image",img1)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
img=cv2.imread("d:/images/sachin.jpg",cv2.IMREAD_COLOR)
img2=cv2.convertScaleAbs(img,alpha=1.5,beta=50)
cv2.imwrite("sachin2.jpg",img2)
cv2.imshow("color image",img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
img=cv2.imread("d:/images/sachin.jpg",cv2.IMREAD_COLOR)
img2=cv2.flip(img,-1)
cv2.imshow("color image2",img2)
cv2.imshow("color image",img)

cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
img=cv2.imread("d:/images/sachin.jpg",cv2.IMREAD_COLOR)
img2=cv2.blur(img,(10,10))
cv2.imshow("color image2",img2)
cv2.imshow("color image",img)

cv2.waitKey()
cv2.destroyAllWindows()